# apiVersion: v1
# kind: Service
# metadata:
#   name: service-nginx
# spec:
#   type: {{ .Values.service.type }}
#   ports:
#     - port: {{ .Values.service.port }}
#       targetPort: 80
#       protocol: TCP
#   selector:
#     app: {{ .Release.Name }}-nginx
